// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzehgudbcvwebhofdyip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6ZWhndWRiY3Z3ZWJob2ZkeWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5Mjc3NDYsImV4cCI6MjA1OTUwMzc0Nn0.ZHHPyD_uNH-334BduOXXbGQKc8Y9rYDJSJ72imMDnqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);